### ISSUE TITLE
Feat: 필터 선택 후 GO 버튼 누를 시 해당 필터 정보 웹으로 보내기

### ISSUE THREAD

**Issue by world2222** [Hipspot/hipspot-mobile#35]
## Description

- Go 버튼을 누를 시 웹으로 선택된 필터(힙스팟, 스터디, 가성비 등등) 정보를 보낼 수 있도록 할 예정입니다.

## Todo

- [x] 필터 정보 웹으로 보내도록 GoButton의 onTap에 구현하기
- [x] 추천 페이지 들어갈 때 배경이 투명하게 나와서 지도와 겹쳐 보이는 버그 수정하기

## References

- Google을 참고하여 개발합니다.

**Comment by yeoularu** [comment]
PR merge
